### ISSUE TITLE
No popup

### ISSUE THREAD

**Issue by ryansnowden** [legomushroom/copy-path-coordinates#1]
Hrm, copied and restarted. Made a new doc. Saved it to Desktop. Made a path with the vector tool. Copy Path etc, asked for authorization. Nothing is copied to clip board.

**Comment by legomushroom** [comment]
@ryansnowden you don't see any error popup also, right?

**Comment by ryansnowden** [comment]
Yup.

Also, the clipboard remains the same (empty or with current string). Have not opened consoles to debug yet, just saw it this morning.

**Comment by legomushroom** [comment]
@ryansnowden what version of `Sketch` do you have? Also is it a trial version? Shoot me the sample file please [legomushroom@gmail.com](mailto:legomushroom@gmail.com).

**Comment by ryansnowden** [comment]
Sketch: Version 3.4.2 (15855)
El Capitan 10.11.1 9 (15B42)

Will email files now.

**Comment by ryansnowden** [comment]
More info:

AppSandbox.authorize(/Users/myusername/copy-svg-path-to-clipboard-tmp/)
– No bookmark found, let's create one
  <626f6f6b a0020000 00000410 30000000 d624c7f8 e6198ad8 9e866d1c 87f55957 4ab56011 b00ed311 4858df17 6cb399db 9c010000 04000000 03030000 00080028 05000000 01010000 55736572 73000000 05000000 01010000 7279616e 73000000 07000000 01010000 4465736b 746f7000 0c000000 01060000 10000000 20000000 30000000 08000000 04030000 ef930200 00000000 08000000 04030000 4edf1900 00000000 08000000 04030000 5fdf1900 00000000 0c000000 01060000 54000000 64000000 74000000 08000000 00040000 41baaa56 14000000 18000000 01020000 02000000 00000000 0f000000 00000000 00000000 00000000 08000000 04030000 01000000 00000000 0b000000 01010000 7279616e 736e6f77 64656e00 04000000 03030000 f6010000 08000000 01090000 66696c65 3a2f2f2f 0c000000 01010000 4d616369 6e746f73 68204844 08000000 04030000 0000005a c3000000 08000000 00040000 41bb7c7b c9000000 24000000 01010000 37353545 45414543 2d383232 442d3345 41412d38 4232442d 45383035 37393834 39324337 18000000 01020000 81000000 01000000 ef130000 01000000 00000000 00000000 01000000 01010000 2f000000 00000000 01050000 cc000000 feffffff 01000000 00000000 10000000 04100000 40000000 00000000 05100000 84000000 00000000 10100000 a8000000 00000000 40100000 98000000 00000000 02200000 88010000 00000000 05200000 f8000000 00000000 10200000 08010000 00000000 11200000 3c010000 00000000 12200000 1c010000 00000000 13200000 2c010000 00000000 20200000 68010000 00000000 30200000 94010000 00000000 01c00000 c8000000 00000000 11c00000 d8000000 00000000 12c00000 ec000000 00000000 10d00000 04000000 00000000>
ReferenceError: Can't find variable: doc
line: 125
sourceURL: /Users/ryans/Library/Containers/com.bohemiancoding.sketch3/Data/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Untitled.sketchplugin
column: 6

Script executed in 7.450255s

**Comment by legomushroom** [comment]
@ryansnowden that's right, when you put the code in custom plugin section it doesn't have the doc variable.

Could you launch "Console" app and see what was output there?

**Comment by ryansnowden** [comment]
Console is empty. All plugins appear in the Plugin menu though, and the DevTools assistant is running in the menu bar. Only thing I can see is a OSX dialog box asking for permissions which might cause some issues with permissions via App Store installations (mine). That and I have no idea what I’m doing with Sketch dev tools.

**Comment by legomushroom** [comment]
@ryansnowden you need to run the Console app, and then select path and launch the plugin. Please try, the console app can not be empty.

**Comment by legomushroom** [comment]
@ryansnowden I'm thinking that the current approach is pretty verbose and depends on system permissions - thus error prone.

I came up with more laconic one if you can test it in `Custom Script` section and it works fine for you, I'll will publish it right away. There is the code:

``` javascript
function copy_text(txt){
  var pasteBoard = [NSPasteboard generalPasteboard]
  [pasteBoard declareTypes:[NSArray arrayWithObject:NSPasteboardTypeString] owner:nil]
  [pasteBoard setString:txt forType:NSPasteboardTypeString]
  return txt;
}

var selection = context.selection;
var layer   = selection[0].layers().objectAtIndex(0),
    rect    = [[layer frame] rect],
    bezier  = [layer bezierPathInRect:rect],
    svg     = [bezier svgAttributes][0] + '';

var str = copy_text( svg.split('"')[1] );
log('SVG path coordinates copied to clipboard');
// [doc showMessage: "SVG path coordinates copied to clipboard"];

```

Thanks!

**Comment by legomushroom** [comment]
@ryansnowden ok pushed this version. It is much better indeed.
Please reopen the issue if it doesn't work for you.

Thanks for the heads up.

**Comment by ryansnowden** [comment]
Will check soon. Severe lack of sleep.
