### ISSUE TITLE
Issue with Sketch 3.7

### ISSUE THREAD

**Issue by legowhales** [legomushroom/copy-path-coordinates#2]
Hi,

It doesn't seem to work at all with the latest Sketch (3.7.2). Have you tried it?

Best regards,
Jeremy

**Comment by legomushroom** [comment]
@jeremylemardele Hi, thanks for heads up. Will look into shortly.

**Comment by legomushroom** [comment]
@jeremylemardele finally got to the bottom of this -- `Sketch app` devs removed a method on `NSBezierPath` interface so I had to put the new on for the plugin. Please reopen this issue if it doesn't work for you now. Thanks!
